# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-release
dist: trusty

os:
  - linux
  - osx

script:
  - R -e 'install.packages("BiocManager")'
  - R -e 'BiocManager::install(version = "3.9")'


#before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
#  deploy:
#    provider: script
#    script: Rscript -e 'pkgdown::deploy_site_github()'
#    skip_cleanup: true
